### PR TITLE
Https fix 2

### PR DESCRIPTION
**Pull request by domoritz**
jQuery also needs to be loaded over https

### CODE REVIEW

**Comment by grant** [comment]
hmm, doesn't seem to be working...

**Comment by domoritz** [comment]
Yeah, I just properly forked. I thought I could do without but the https gods are angry with me.

**Comment by domoritz** [comment]
@grant Sorry about that. I can't really test but maybe you have to reset the change I made in https://github.com/grant/is-gitlab-down/blob/gh-pages/index.js#L59

I don't know why gitlab would send an `Access-Control-Allow-Origin` header in one case but not the other.

**Comment by domoritz** [comment]
httpseverywhere can be annoying ;-)

**Pull request merged**
